FROM maven:3.6.3-jdk-11
EXPOSE 8080
WORKDIR /app
RUN git clone https://code.samourai.io/whirlpool/whirlpool-server.git
WORKDIR /app/whirlpool-server
RUN mvn clean install -Dmaven.test.skip=true
COPY custom.properties /app/whirlpool-server/config.properties
RUN mkdir /app/logs && touch /app/logs/mixs.csv && touch /app/logs/activity.csv
CMD java -jar target/whirlpool-server-0.23.36.jar --spring.config.location=config.properties
